version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
      - '3131:3131'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    pull_policy: never
    build: ./postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}